#!/usr/bin/env php
<?php

$composerAutoload = false;
foreach (array(__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php') as $file) {
    if (file_exists($file)) {
        $composerAutoload =  $file;
        break;
    }
}

if (!$composerAutoload) {
    fwrite(STDERR,
        'You need to set up the project dependencies using the following commands:' . PHP_EOL .
        'wget http://getcomposer.org/composer.phar' . PHP_EOL .
        'php composer.phar install' . PHP_EOL
    );
    die(1);
}

/** @noinspection PhpIncludeInspection */
require $composerAutoload;

use SWebhosting\GithubBackup\Command\BackupCommand;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new BackupCommand());
$application->run();
